sudo: required

language: bash

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" -y install docker-engine

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - echo $TRAVIS_TAG > VERSION
  - docker -v
  - docker-compose -v
  - docker-compose build

script:
  - docker-compose run tests sh -c 'sleep 60 & /code/tests/run.sh'

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: "KPWxFNnp+ApxknuDFcq6bYWwxS3ZONt/3ARcAEOwRB1pH4Kvyi7z5t4njUOGN/BCsG81rRff2vLsGDzG7SZvrtSQaN8Qk49WzOYUDa+82wmaHlYcUjVRVke/XBvoQJTP2ed3FEbxQvXclHa55oD4T6FOoDNeX9aKDixFlRjL849V9ExucCn6Dmqcnwfz7DNnL+zfvXRvOwN5wsUdCN3v31xqToQ++CImHbnHI+u2IqdH/AF5uxyMtR5KqZKr6tlg3q9gTAeSU3NH2WRUTPILKxgtSjcCQTMRHJtNLXf+KSz+Y7yYEVqcxBjjonRHUtaadXinAFQJerv9ivLfxxQvcQgCaF6jXfkNDzWhXxOfieZP8fr1/7jNg53o5HGiR1ufYiY6yM+VMxUF7okUJlE25H2w79+JqJK1dg1Pg4m01s57JfNpCYM3g8zffkuVAri2AM8f65CKiEyELF1S7W4j+O0mO6jAirGx1X1gChXxS+Qv7znTXh2T1OGMWYG8sL1OCnUcLqMB0OpapjdJptbmDdE0b4V+YIxmi+QlPcyG3mnJ5ivT5vyLxu0YtOQJoSs864MX6jX2YZkcX/xTe4NeFylnJ5Nd9vpN6vFV90BVPV8O1gbMBSKMUj1O7YW/zmitpXtcOYCGHmLeUiJ38GLXN2Jkuw/9thUlnCyES0PtAVI="
