FROM alpine:3.4

RUN apk --update add bash curl openjdk7-jre git openssl git python

RUN mkdir /app

WORKDIR /app

RUN wget https://github.com/OpenRefine/OpenRefine/releases/download/2.6-rc.2/openrefine-linux-2.6-rc.2.tar.gz && \
    tar xzf openrefine-linux-2.6-rc.2.tar.gz && \
    rm -f openrefine-linux-2.6-rc.2.tar.gz

RUN wget https://bootstrap.pypa.io/get-pip.py && python ./get-pip.py
RUN git clone https://github.com/PaulMakepeace/refine-client-py

WORKDIR /app/refine-client-py

RUN pip install -r requirements.txt

COPY ./src /code

CMD /code/run-refine-client-py.sh
