version: '2'
services:
  openrefine-transformation:
    build:
      context: .
      dockerfile: Dockerfile
    image: keboola/openrefine-transformation
    tty: true
    stdin_open: true
    command: /code/scripts/run.sh
    network_mode: bridge
    volumes:
      - ./data:/data
      - .:/code

  devel:
    image: keboola/openrefine-transformation
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
      - .:/code
    ports:
      - "3333:3333"
    command: /app/OpenRefine-2.6-rc.2/refine -m 8192m -i 0.0.0.0

  tests:
    image: keboola/openrefine-transformation
    tty: true
    stdin_open: true
    command: /code/tests/run.sh
    volumes:
      - .:/code
    links:
      - devel
    environment:
      - OPENREFINE_HOST=devel
      - OPENREFINE_PORT=3333
